version: '3.1'
services:
    postgres:
         image: postgres
         restart: always
         environment:
               POSTGRES_PASSWORD: admin123
         ports:
                 - "5432:5432"
    redis:
         image: redis
         
